# Generated by Django 4.2.2 on 2024-09-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('number_home', models.CharField(max_length=50, verbose_name='номер дома')),
                ('level_company', models.IntegerField(default=0, verbose_name='уровень компании')),
                ('type_company', models.CharField(choices=[('individual', 'индивидуальный'), ('factory', 'завод'), ('retail', 'розничный')], max_length=30, verbose_name='тип компании')),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя компании')),
                ('supplier_id', models.IntegerField(blank=True, null=True, verbose_name='id компании поставщика')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец компании')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя компании-поставщика')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('company_customer', models.IntegerField(verbose_name='компания-заказчик')),
                ('company_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='компания-поставщик')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
    ]
